export type Quote = {
  content: string
  author: string
}

export const quotes: Quote[] = [
  { content: 'First, solve the problem. Then, write the code.', author: 'John Johnson' },
  { content: 'Programs must be written for people to read, and only incidentally for machines to execute.', author: 'Harold Abelson' },
  { content: 'Talk is cheap. Show me the code.', author: 'Linus Torvalds' },
  { content: 'Simplicity is prerequisite for reliability.', author: 'Edsger W. Dijkstra' },
  { content: 'Before software can be reusable it first has to be usable.', author: 'Ralph Johnson' },
  { content: 'Make it work, make it right, make it fast.', author: 'Kent Beck' },
  { content: 'Premature optimization is the root of all evil.', author: 'Donald Knuth' },
  { content: 'Controlling complexity is the essence of computer programming.', author: 'Brian Kernighan' },
  { content: 'Code is like humor. When you have to explain it, it is bad.', author: 'Cory House' },
  { content: 'The best error message is the one that never shows up.', author: 'Thomas Fuchs' },
  { content: 'Deleted code is debugged code.', author: 'Jeff Sickel' },
  { content: 'Good code is its own best documentation.', author: 'Steve McConnell' },
  { content: 'The function of good software is to make the complex appear to be simple.', author: 'Grady Booch' },
  { content: 'Any fool can write code that a computer can understand. Good programmers write code that humans can understand.', author: 'Martin Fowler' },
  { content: 'Fix the cause, not the symptom.', author: 'Steve Maguire' },
  { content: 'The most damaging phrase in software development is: it works on my machine.', author: 'Vidiu Platon' },
  { content: 'Testing leads to failure, and failure leads to understanding.', author: 'Burt Rutan' },
  { content: 'Software is a great combination between artistry and engineering.', author: 'Bill Gates' },
  { content: 'The way to get started is to quit talking and begin doing.', author: 'Walt Disney' },
  { content: 'Small steps every day compound into big results.', author: 'Anonymous' },
  { content: 'If debugging is the process of removing software bugs, then programming must be the process of putting them in.', author: 'Edsger W. Dijkstra' },
  { content: 'The sooner you start to code, the longer the program will take.', author: 'Roy Carlson' },
  { content: 'Experience is the name everyone gives to their mistakes.', author: 'Oscar Wilde' },
  { content: 'The only way to learn a new programming language is by writing programs in it.', author: 'Dennis Ritchie' },
  { content: 'The most important property of a program is whether it accomplishes the intention of its user.', author: 'C.A.R. Hoare' },
  { content: 'A primary cause of complexity is that software vendors uncritically adopt almost any feature that users want.', author: 'Niklaus Wirth' },
  { content: 'One of my most productive days was throwing away 1000 lines of code.', author: 'Ken Thompson' },
  { content: 'It is better to wait for a productive programmer to become available than to wait for the first available programmer to become productive.', author: 'Steve McConnell' },
  { content: 'There are only two kinds of languages: the ones people complain about and the ones nobody uses.', author: 'Bjarne Stroustrup' },
  { content: 'The best performance improvement is the transition from the nonworking state to the working state.', author: 'John Ousterhout' },
  { content: 'Walking on water and developing software from a specification are easy if both are frozen.', author: 'Edward V. Berard' },
  { content: 'If builders built buildings the way programmers wrote programs, then the first woodpecker that came along would destroy civilization.', author: 'Gerald Weinberg' },
  { content: 'When in doubt, use brute force.', author: 'Ken Thompson' },
  { content: 'Computers are fast; developers keep them slow.', author: 'Anonymous' },
  { content: 'Complexity kills. It sucks the life out of developers.', author: 'Ray Ozzie' },
  { content: 'Readable code is easier to maintain than clever code.', author: 'Anonymous' },
  { content: 'Design is about making trade-offs, not about perfection.', author: 'Anonymous' },
  { content: 'Every great developer you know got there by solving problems they were unqualified to solve.', author: 'Patrick McKenzie' },
  { content: 'Consistency is what turns good engineering into great products.', author: 'Anonymous' },
  { content: 'Ship small, learn fast, improve continuously.', author: 'Anonymous' },
]
